POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "username":"lolalola ",
  "password": "sajkhj",
  "name" : "lolita lola"
}

###

POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "password": "iniesta",
  "name" : "andres"
}

###


POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "name" : "andres",
  "password":"",
  "username":""
}

###