POST http://localhost:8080/api/blogs/
Content-Type: application/json

{
  "title":"Request with no user",
  "author": "Threepeat",
  "url":"JS.com",
  "likes": 5000
 }

###

POST http://localhost:8080/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImluaWVzdGE4IiwiaWQiOiI2NDU4ZTcxZTc1YzQyOTI3YzZlYjkwMzQiLCJpYXQiOjE2ODY2Njk5NDAsImV4cCI6MTY4NjY3MzU0MH0.eru4hmuAx4MEvmfJuVAlIweDusZjalYp7YYhJc_MfNo


{
  "title":"React Blog",
  "author": "Andres Iniesta",
  "url":"React.com"
}

###

POST http://localhost:8080/api/blogs/
Content-Type: application/json

{
  "author": "Threepeat",
  "url":"JS.com",
  "likes": 5000,
  "user":"6454006c3ca425590b26bfac" 
   
}

###

