POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "username":"MM93",
  "password": "1234",
  "name" : "Marc Marquez"
}

###

POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "password": "iniesta",
  "name" : "andres"
}

###


POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "name" : "andres",
  "password":"",
  "username":""
}

###