POST http://localhost:8080/api/blogs/
Content-Type: application/json

{
  "title":"Request with no user",
  "author": "Threepeat",
  "url":"JS.com",
  "likes": 5000
 }

###

POST http://localhost:8080/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImluaWVzdGE4IiwiaWQiOiI2NDU4ZTcxZTc1YzQyOTI3YzZlYjkwMzQiLCJpYXQiOjE2ODM3MDA4MzcsImV4cCI6MTY4MzcwNDQzN30.AFeP_hXXMZ8TcIpRea82QwBmMSsN2YznzHXbj6Qa6_4


{
  "title":"WEdnesday blog",
  "author": "Threepeat",
  "url":"JS.com"
}

###

POST http://localhost:8080/api/blogs/
Content-Type: application/json

{
  "author": "Threepeat",
  "url":"JS.com",
  "likes": 5000,
  "user":"6454006c3ca425590b26bfac" 
   
}

###

