POST http://localhost:8080/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lc3NpIiwiaWQiOiI2NDQyMzMyZTVjOWU5ODJlNGMzZGVhNWEiLCJpYXQiOjE2ODQzMTg5MjYsImV4cCI6MTY4NDMyMjUyNn0.jeOKT9gQbWVjnNMTKXKfY-r1Z_ggkeUiDBjgozMIwjY

{
  "content":"THIRD messi NOTE",
  "important": false
}

###

POST http://localhost:8080/api/notes/
Content-Type: application/json

{
  "important":"false"
  }

###
POST http://localhost:8080/api/notes/
Content-Type: application/json

