POST  http://localhost:3001/api/persons 
Content-Type: application/json

{
"name":"Albert Einstein", "number": "1234-7654"
}

###

POST  http://localhost:3001/api/persons 
Content-Type: application/json

{
"name":"Mike Smith", "number": "242-45"
}

###

POST http://localhost:3001/api/persons/ 
Content-Type: application/json

{
"number":"123"
}

###
POST http://localhost:3001/api/persons/ 
Content-Type: application/json

{
"name":"Greta"
}

###
POST http://localhost:3001/api/persons/ 
Content-Type: application/json



